### ISSUE TITLE
prototype pollution vulnerability

### ISSUE THREAD

**Issue by ChiralMichael** [TehShrike/deepmerge#158]
Deepmerge has prototype pollution issues. Both what recently hit lodash, as well as merging objects containing '\_\_proto\_\_' definitions. Repros are in the link and elsewhere.

https://snyk.io/blog/snyk-research-team-discovers-severe-prototype-pollution-security-vulnerabilities-affecting-all-versions-of-lodash/

**Comment by ChiralMichael** [comment]
Sorry, this is a mistake. I will have a positive repro before re-opening.

**Comment by macdja38** [comment]
@ChiralMichael Please report vulnerabilities in a private fashion so that we have at least some time to decide how to fix them before releasing the info publicly along with a patched version.

At the moment I don't think we really have a good way of security vulnerabilities, we'll try and come up with something soon.

**Comment by ChiralMichael** [comment]
Jake,

Makes sense, I will do in the future. At any rate, I retract the
vulnerability, further investigates shows that you are fine. I am sorry for
the spam.

--michael
